apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: discord-bot
spec:
  selector:
    matchLabels:
      app: discord-bot
      tier: redis 
  replicas: 1
  template:
    metadata:
      labels:
        app: discord-bot
        tier: redis 
    spec:
      containers:
        - name: redis
          image: redis:5.0.7-alpine
          command:
            - redis-server
          env:
          - name: MASTER
            value: "true"
          ports:
          - containerPort: 6379